name: Linting
permissions:
  contents: read
on: push
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v7
      - name: Use Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
      - name: Install pnpm
        uses: pnpm/action-setup@v6
      - name: Install dependencies
        run: pnpm install
      - name: Run ESLint
        run: pnpm lint
      - name: Run Prettier
        run: pnpm prettier:check
        if: success() || failure()
